# 异常处理

> 异常处理时指预估代码执行过程中可能发生的错误，然后最大程度的避免错误的发生导致整个程序无法继续运行

## throw 抛出异常

使用`throw`关键字抛出异常，它会中止程序

throw关键字经常和 Error 对象配合使用

```javascript
function counter(x, y) {
	if (!x || !y) {
		// throw '参数不能为空！';
		throw new Error('参数不能为空！');
	}
	return x + y
}
counter();
```

## try...catch捕获异常，finally执行程序

1. 可以通过 `try...catch` 捕获错误信息（浏览器提供的错误信息）

2. 将预估可能发生错误的代码写在 try 代码段中

3. 如果` try `代码中出现错误后，会执行 cathch代码段，并截获到错误信息

   - 利用`catch`的参数调用错误信息

4. `finally` 不管程序是否有错误，都会执行

   ```javascript
   <p>123</p>
   
   function fn() {
       try {
           // 可能发送错误的代码，要写到 try
           const p = document.querySelector('.p');     // 例如('.p')写成类选择器
           p.style.color = 'red';
       } catch (err) {    // err 是一个形参，catch()必须带形参，错误信息会传递到形参
           // 拦截错误，提示浏览器提供的错误信息，但是不中断程序的执行
           console.log(err.message);       // message 固定写法
           throw new Error('选择器错误！');    // 可以添加throw抛出异常
           // catch里需要加return 或 throw 中断程序 
       }
       finally {
           // 不管程序对不对，一定会执行的代码
           alert('弹出对话框')
       }
       console.log(11);
   }
   fn();
   ```

## debugger

**`debugger` 语句**调用任何可用的调试功能，例如设置断点。如果没有调试功能可用，则此语句不起作用

- 当 debugger 被调用时，执行暂停在 `debugger` 语句的位置

  ```javascript
  function fn() {
      debugger;
      console.log(11);
  };
  fn();
  ```

  

